[package]
name = "cvars"
version = "0.0.0"
authors = ["Martin Taibr <taibr.martin@gmail.com>"]
edition = "2018"
description = "Configuration variables for games"
homepage = "https://github.com/martin-t/cvars"
repository = "https://github.com/martin-t/cvars"
license = "AGPL-3.0-or-later"
readme = "README.md"
keywords = ["gamedev", "config", "settings", "const-tweaker", "debugging"]
categories = ["game-development"]

[dependencies]
