[package]
name = "cvars"
version = "0.1.0"
edition = "2018" # TODO
authors = ["Martin Taibr <taibr.martin@gmail.com>"]
description = "Configuration variables for games"
homepage = "https://github.com/martin-t/cvars"
repository = "https://github.com/martin-t/cvars"
license = "AGPL-3.0-or-later"
readme = "README.md" # TODO
keywords = ["configuration", "console", "debugging", "gamedev", "settings"]
categories = [
    "config",
    "command-line-interface",
    "development-tools::procedural-macro-helpers",
    "game-development",
    "rust-patterns",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cvars-macros = { path = "../cvars-macros" }
