[package]
name = "cvars-console-fyrox"
version = "0.1.0"
edition = "2021"

[dependencies]
cvars-console = { path = "../cvars-console" }
#fyrox = "0.27.1"
fyrox = { git = "https://github.com/FyroxEngine/Fyrox", rev = "7d1b8f1733a7a043c779f5767b6c92777404a5f4" }
