[package]
name = "cvars-console-fyrox"
version = "0.1.0"
edition = "2021"

[dependencies]
cvars-console = { path = "../cvars-console" }
fyrox-ui = { git = "https://github.com/FyroxEngine/Fyrox", rev = "102ec67c7ab86cb993864d51c49069dca0ec0fd0" }
