[package]
name = "cvars-console-fyrox"
version = "0.1.0"
edition = "2021"

[dependencies]
cvars-console = { path = "../cvars-console" }
fyrox-ui = { git = "https://github.com/FyroxEngine/Fyrox", rev = "fe402974da2ba3305518660c6efaea96ea185e2a" }
