name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    # Runs at 15:00 UTC on Fri 
    - cron: "0 15 * * 5"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Print versions
        run: rustc --version && cargo --version && wasm-pack --version
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose --all-features

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Print version
        run: cargo fmt --version
      - name: Check formatting
        run: cargo fmt -- --check

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Print version
        run: cargo clippy --version
      - name: Run clippy
        # Technically --all-features doesn't check all code when something is *disabled* by a feature
        # but that is discouraged and no such feature existed at the time this was added.
        run: cargo clippy --all-features -- --deny warnings

  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/install@v0.1
        with:
          crate: cargo-audit
          version: latest
      - name: Print version
        run: cargo audit --version
      - name: Run audit
        run: cargo audit --deny warnings
