name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    # Runs at 15:00 UTC on Fri 
    - cron: "0 15 * * 5"

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # 1.54 is needed for #![doc = include_str!("README.md")]
        # If that was removed, then MSRV would probably be 1.36 which is needed for trybuild (dev-dep)
        # or 1.31 for syn.
        rust: [nightly, stable, 1.54.0]

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      - run: rustc --version && cargo --version
      - run: cargo build --verbose
      - run: cargo test --verbose --all-features

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cargo fmt --version
      - run: cargo fmt -- --check

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cargo clippy --version
        # Technically --all-features doesn't check all code when something is *disabled* by a feature
        # but that is discouraged and no such feature existed at the time this was added.
      - run: cargo clippy --all-features -- --deny warnings

  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/install@v0.1
        with:
          crate: cargo-audit
          version: latest
      - run: cargo audit --version
      - run: cargo audit --deny warnings

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - run: rustc --version && cargo --version
      - run: cargo doc --all-features
        env:
          RUSTDOCFLAGS: --deny warnings
